replicaCount: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

nodeSelector:
  worker.gardener.cloud/pool: llm


tolerations:
  - key: "llm-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "4"
    memory: "12Gi"
  limits:
    cpu: "8"
    memory: "24Gi"

model:
  enabled: true
  repoId: "TheBloke/dolphin-2.6-mistral-7B-GGUF"
  filename: "dolphin-2.6-mistral-7b.Q4_K_M.gguf"
  downloadUrl: "https://huggingface.co/TheBloke/dolphin-2.6-mistral-7B-GGUF/resolve/main/dolphin-2.6-mistral-7b.Q4_K_M.gguf"

extraArgs:
  - "-m"
  - "/models/dolphin-2.6-mistral-7b.Q4_K_M.gguf"
  - "-c"
  - "4096"
  - "-t"
  - "8"
  - "--port"
  - "8080"
  - "--host"
  - "0.0.0.0"

